### ISSUE TITLE
Should `CachedRef` not include `WorldRef<'a>`

### ISSUE THREAD

**Issue by andrewgazelka** [Indra-db/flecs-ecs-rs#125]
https://github.com/Indra-db/flecs-ecs-rs/blob/985ef136ccbdd24a191f0d16f19ed88fed576416/flecs_ecs/src/core/components/cached_ref.rs#L10-L14

I'm wondering if it should include a reference to a world. Because say I'm doing things in a multi-threaded system: Say there's eight stages, eight threads. If I create a cache reference from one world stage, would there curently be an issue accessing it from a different thread with the current setup? I'm not really sure how this all works. 

Also, cache references are generally going to be stored somewhere, I'm thinking. So it's nice if you don't have to have lifetimes for them.

**Comment by Indra-db** [comment]
This would require you to pass in world on the `get` functions. This currently follows the C++ design.

**Comment by Indra-db** [comment]
closing this following my previous comment
