### ISSUE TITLE
Better interface to `defer_begin` / `defer_end`?

### ISSUE THREAD

**Issue by waywardmonkeys** [Indra-db/flecs-ecs-rs#32]
It might be nice to be able to have a `World::defer` and call it with a closure / function which would wrap it in `defer_begin` / `defer_end` calls.

This might not interact as well with `defer_suspend` / `defer_resume`, but maybe that's less important.

**Comment by Indra-db** [comment]
this already exists for quite some time, 

<img width="548" alt="image" src="https://github.com/Indra-db/flecs-ecs-rs/assets/60851042/e93f2b99-872b-444a-85da-d623cf36069b">

in case you wonder "does this function exist from the `cpp api`" you can do a search generally from `[cpp class name]::[function name]`
