### ISSUE TITLE
Document `each_iter`

### ISSUE THREAD

**Issue by andrewgazelka** [Indra-db/flecs-ecs-rs#84]
https://github.com/Indra-db/flecs-ecs-rs/blob/727b5378994070c9ddd8cc251801b640a113a925/flecs_ecs/src/core/utility/traits/iter.rs#L124

https://github.com/Indra-db/flecs-ecs-rs/blob/727b5378994070c9ddd8cc251801b640a113a925/flecs_ecs/src/core/utility/traits/reactor.rs#L56

The second (1-indexed `usize`) parameter is slightly confusing. I am guessing it is the iteration number we are on.

**Comment by Indra-db** [comment]
done
